version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  backend:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app/src
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
